import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { TrackJSAgent } from "trackjs-nextjs"

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TrackJS in NextJS 15+",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <TrackJSAgent config={{
          token: "YOUR_TOKEN"
        }} />
      </head>
      <body>
        <main className={"main"}>{children}</main>
      </body>
    </html>
  );
}