import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { TrackJS, TrackJSInstall } from "./trackjs-loader";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

TrackJSInstall();

export const metadata: Metadata = {
  title: "TrackJS in NextJS 14+",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className={"main"}>{children}</main>
      </body>
    </html>
  );
}